### ISSUE TITLE
Open folded group on moving to it

### ISSUE THREAD

**Issue by fenuks** [Nudin/anki_vimove#1]
Anki allows grouping decks by naming it like `English::words` and `Spanish::words`. Groups can be closed.
If I have group like so:
```
- English
   words
+ Spanish
```
, and I press <kdb>j</kdb> twice while I am and `English::word`, cursor will move to `Spanish::words`, but group will not open, so I will not see that. It would be convenient if group automatically opened, and if there were mapping to open/close them (vim has `zo` and `zc` for folds, I think these would be great provided Anki allows registering broken shortcuts).

**Comment by Nudin** [comment]
Yes, this wasn't nice. I now fixed this. But I solved it the other way: if you move with j/k they will jump over the hidden decks. Additionally, there are now keybindings to open/close the current deck. Since Qt allows only single key-shortcuts and 'z' might be useful for other features I used `+` and `-` – both will toggle the state.

**Comment by fenuks** [comment]
Thank you! I just tested it, and it works very well. Shame that Qt has such limitation, but your shortcuts choice is quite intuitive. Personally I would prefer <kbd>h</kbd> to collapse and <kbd>l</kbd> to uncollapse (perhaps less intuitive, but easier to type), but that's a minor problem, I can easily change it in my copy of the addon. Thank you again.

**Comment by Nudin** [comment]
@fenuks The newest version allows to configure the shortcuts. So you don't need to maintain a fork just to have your preferred key bindings.

**Comment by fenuks** [comment]
That's very thoughtful of you, thank you! It wasn't much of a hassle to change these on each update, but naturally I'm happy that now I can redefine them in ‘official’ way. :)
