### ISSUE TITLE
Error after latest update

### ISSUE THREAD

**Issue by Positron010** [Nudin/anki_vimove#2]
Hi,
Thanks for the addon.

After updating to the latest version, I encountered this error, whenever I open Anki:

```
When loading '⁨vi-like movement in deck browser⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 210, in loadAddons
  File "...\Anki2\addons21\1997961715\__init__.py", line 162, in <module>
    for key, action in config["keys"].items():
TypeError: 'NoneType' object is not subscriptable
```

My Anki version is **2.1.44**

Thanks

**Comment by Nudin** [comment]
Sorry for the inconvenience. Can you open the addons configuration (can be found in the extension manager) and copy the content? And try to press "Restore defaults" and see what happens. If that doesn't work, you can fix it by entering the default config from [here](https://github.com/Nudin/anki_vimove/blob/main/config.json).

**Comment by Positron010** [comment]
Hi again, 
The config button of the addon is not clickable in the addons configuration. I uninstalled the addon and installed it again, and got the same error.

Thanks

**Comment by Positron010** [comment]
I am not sure if the problem is from my side, but there is no `config.json` file in the addon folder. I downloaded the addon from this link:

https://ankiweb.net/shared/info/1997961715

**Comment by Nudin** [comment]
Ah, stupid mistake of me, I just forgot to add that file to the zip. If you update it now should work.

**Comment by Positron010** [comment]
Hey,
Sorry for the late reply. 
The issue has been fixed. Thanks a lot!
